/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelleryshop.bill;

import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jewelleryshop.object.ErrorHandler;
import jewelleryshop.object.Order_db;
import jewelleryshop.object.Stock_db;
import jewelleryshop.object.XMLCart;

/**
 *
 * @author Prashant Kumar Prasad
 */
public class Order extends javax.swing.JDialog {

    /**
     * Creates new form Order
     */
    ErrorHandler error = new ErrorHandler();
    Order_db order = new Order_db();
    Stock_db stock = new Stock_db();
    XMLCart cart = new XMLCart("cart.xml");
    String date;

    public Order(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());

        date = new SimpleDateFormat("dd-MM-yyyy").format(new Date(System.currentTimeMillis()));
        newOrderDate.setText(date);
        editOrderDate.setText(date);
        newOrderID.setText(order.getAutoIncriment());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        newOrderID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newOrderCname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newOrderItem = new javax.swing.JComboBox<>();
        newOrderMetal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newOrderNotes = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        newOrder = new javax.swing.JButton();
        newOrderCaddress = new javax.swing.JTextField();
        newOrderDate = new javax.swing.JFormattedTextField();
        newOrderPh = new javax.swing.JFormattedTextField();
        newOrderWeight_min = new javax.swing.JFormattedTextField();
        newOrderWeight_max = new javax.swing.JFormattedTextField();
        newOrderAdvance = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        editOrderID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        editOrderCname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        editOrderNotes = new javax.swing.JTextArea();
        editOrderItem = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        editOrder = new javax.swing.JButton();
        editOrderMetal = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        editOrderCaddress = new javax.swing.JTextField();
        editOrderDate = new javax.swing.JFormattedTextField();
        editOrderPh = new javax.swing.JFormattedTextField();
        editOrderWeight_max = new javax.swing.JFormattedTextField();
        editOrderWeight_min = new javax.swing.JFormattedTextField();
        editOrderAdvance = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        orderCompleteID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        completeOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetails = new javax.swing.JList<>();
        orderCompleteWeight = new javax.swing.JFormattedTextField();
        orderCompletePrice = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jewellery Work Order");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Order No  #");

        newOrderID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Date");

        newOrderCname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Costumer Name");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Ph");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Item");

        newOrderItem.setEditable(true);
        newOrderItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newOrderItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ring", "Nackless", "Chain", "Jhumka", "Bali" }));

        newOrderMetal.setEditable(true);
        newOrderMetal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newOrderMetal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold", "Silver", "Bronze", "Copper", "Other" }));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Type");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("to");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Weight Range");

        newOrderNotes.setColumns(10);
        newOrderNotes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newOrderNotes.setRows(3);
        jScrollPane2.setViewportView(newOrderNotes);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Notes");

        newOrder.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newOrder.setText("Place a Order");
        newOrder.setSelected(true);
        newOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newOrderMouseClicked(evt);
            }
        });

        newOrderCaddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        newOrderDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        newOrderDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        newOrderPh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0000000000"))));
        newOrderPh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        newOrderWeight_min.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        newOrderWeight_min.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        newOrderWeight_max.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        newOrderWeight_max.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        newOrderAdvance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        newOrderAdvance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Advance Money");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newOrder))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel23))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newOrderAdvance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newOrderWeight_min, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newOrderWeight_max))
                            .addComponent(newOrderMetal, 0, 150, Short.MAX_VALUE)
                            .addComponent(newOrderItem, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newOrderCname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newOrderCaddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newOrderID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newOrderDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newOrderPh, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newOrderCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newOrderCaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newOrderPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newOrderMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(newOrderWeight_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newOrderWeight_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newOrderAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newOrder)
                .addContainerGap())
        );

        jTabbedPane1.addTab("New", jPanel1);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Order No  #");

        editOrderID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editOrderID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editOrderIDKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Date");

        editOrderCname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Costumer Name");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Address");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Ph");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("to");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Weight Range");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Item");

        editOrderNotes.setColumns(10);
        editOrderNotes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editOrderNotes.setRows(3);
        jScrollPane4.setViewportView(editOrderNotes);

        editOrderItem.setEditable(true);
        editOrderItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editOrderItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ring", "Nackless", "Chain", "Jhumka", "Bali" }));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Notes");

        editOrder.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editOrder.setText("Modify");
        editOrder.setActionCommand("");
        editOrder.setSelected(true);
        editOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editOrderMouseClicked(evt);
            }
        });

        editOrderMetal.setEditable(true);
        editOrderMetal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editOrderMetal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold", "Silver", "Bronze", "Copper", "Other" }));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Type");

        editOrderCaddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        editOrderDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        editOrderDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        editOrderPh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0000000000"))));
        editOrderPh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        editOrderWeight_max.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        editOrderWeight_max.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        editOrderWeight_min.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        editOrderWeight_min.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        editOrderAdvance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        editOrderAdvance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Advance Money");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editOrder))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editOrderAdvance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(editOrderWeight_min, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editOrderWeight_max))
                            .addComponent(editOrderMetal, 0, 150, Short.MAX_VALUE)
                            .addComponent(editOrderItem, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editOrderCname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editOrderCaddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editOrderDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editOrderPh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editOrderID, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(editOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOrderCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(editOrderCaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(editOrderPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOrderMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(editOrderWeight_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOrderWeight_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOrderAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editOrder)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modify", jPanel2);

        orderCompleteID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        orderCompleteID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orderCompleteIDKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Order No");

        completeOrder.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        completeOrder.setText("Complete This Order");
        completeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                completeOrderMouseClicked(evt);
            }
        });

        orderDetails.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(orderDetails);

        orderCompleteWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        orderCompleteWeight.setEnabled(false);
        orderCompleteWeight.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        orderCompletePrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        orderCompletePrice.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Final Weight");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Making and Other Charges");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(completeOrder))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderCompleteWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(orderCompletePrice)
                            .addComponent(orderCompleteID))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCompleteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCompleteWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCompletePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(completeOrder)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Complete Order", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Jewellery Works Order");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newOrderMouseClicked
        if (!newOrderID.getText().isEmpty() && !newOrderDate.getText().isEmpty() && !newOrderCname.getText().isEmpty() && !newOrderCaddress.getText().isEmpty() && !newOrderPh.getText().isEmpty() && !newOrderWeight_min.getText().isEmpty() && !newOrderAdvance.getText().isEmpty()) {
            int o_id = Integer.parseInt(newOrderID.getText());
            String o_date = newOrderDate.getText();
            String o_cname = newOrderCname.getText().trim(), o_add = newOrderCaddress.getText().trim();
            String o_ph = newOrderPh.getText();
            String o_item = newOrderItem.getSelectedItem().toString();
            String o_metal = newOrderMetal.getSelectedItem().toString();
            float o_min_wt = Float.parseFloat(newOrderWeight_min.getText());
            float o_max_wt = Float.parseFloat(newOrderWeight_max.getText());
            float o_advance = Float.parseFloat(newOrderAdvance.getText());
            String o_notes = newOrderNotes.getText().trim();

            int i;
            i = order.insert(o_id, o_date, o_cname, o_add, o_ph, o_item, o_metal, o_min_wt, o_max_wt, o_advance, o_notes);
            if (i == 1) {
                cart.add(o_id + " ".trim(), o_item, "order", o_advance + " ".trim());
            }
            error.SQLError(i);
        } else {
            error.SomethingMissing();
        }
    }//GEN-LAST:event_newOrderMouseClicked

    private void editOrderIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editOrderIDKeyReleased
        if (!editOrderID.getText().isEmpty()) {
            String result[] = order.getOrderDetails(editOrderID.getText());
            editOrderDate.setText(result[1]);
            editOrderCname.setText(result[2]);
            editOrderCaddress.setText(result[3]);
            editOrderPh.setText(result[4]);
            editOrderItem.setSelectedItem(result[5]);
            editOrderMetal.setSelectedItem(result[6]);
            editOrderWeight_min.setText(result[7]);
            editOrderWeight_max.setText(result[8]);
            editOrderAdvance.setText(result[11]);
            editOrderNotes.setText(result[12]);

        }
    }//GEN-LAST:event_editOrderIDKeyReleased

    private void editOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editOrderMouseClicked
        if (!editOrderID.getText().isEmpty()) {
            if (!editOrderID.getText().isEmpty() && !editOrderDate.getText().isEmpty() && !editOrderCname.getText().isEmpty() && !editOrderCaddress.getText().isEmpty() && !editOrderPh.getText().isEmpty() && !editOrderWeight_min.getText().isEmpty() && !editOrderAdvance.getText().isEmpty()) {
                int o_id = Integer.parseInt(editOrderID.getText());
                String o_date = editOrderDate.getText();
                String o_cname = editOrderCname.getText().trim(), o_add = editOrderCaddress.getText().trim();
                String o_ph = editOrderPh.getText();
                String o_item = editOrderItem.getSelectedItem().toString();
                String o_metal = editOrderMetal.getSelectedItem().toString();
                float o_min_wt = Float.parseFloat(editOrderWeight_min.getText());
                float o_max_wt = Float.parseFloat(editOrderWeight_max.getText());
                float o_advance = Float.parseFloat(editOrderAdvance.getText());
                String o_notes = editOrderNotes.getText().trim();

                int i;
                i = order.update(o_id, o_date, o_cname, o_add, o_ph, o_item, o_metal, o_min_wt, o_max_wt, o_advance, o_notes);
                error.SQLError(i);
            } else {
                error.SomethingMissing();
            }
        }
    }//GEN-LAST:event_editOrderMouseClicked

    private void orderCompleteIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderCompleteIDKeyReleased
        if (!orderCompleteID.getText().isEmpty()) {
            String result[] = order.getOrderDetails(orderCompleteID.getText());
            String stockDetails[] = stock.getStockDetails(result[9]);
            
            DefaultListModel<String> lm = new DefaultListModel<>();
            lm.addElement("Date : " + result[1]);
            lm.addElement("Name : " + result[2]);
            lm.addElement("Address : " + result[3]);
            lm.addElement("Phone : " + result[4]);
            lm.addElement("Item : " + result[5]);
            lm.addElement("Metal :" + result[6]+" (Made :"+stockDetails[3]+")");
            lm.addElement("Weaght Range : " + result[7] + "gm - " + result[8] + "gm");
            lm.addElement("Advance : " + result[11]);
            lm.addElement("Notes : " + result[12]);
            lm.addElement("Status : " + result[13]);
            
            orderCompleteWeight.setText(stockDetails[4]);
            orderDetails.setModel(lm);
        }
    }//GEN-LAST:event_orderCompleteIDKeyReleased

    private void completeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completeOrderMouseClicked
        if (!orderCompleteID.getText().isEmpty() && !orderCompleteWeight.getText().isEmpty() && !orderCompletePrice.getText().isEmpty()) {
            String result[] = order.getOrderDetails(orderCompleteID.getText());
            if (result[0] == null ? orderCompleteID.getText() == null : result[0].equals(orderCompleteID.getText())) {
                // to avoid null pointer error
                if (result[13].equals("In Stock")) {
                    int res = order.complete(Integer.parseInt(result[0]), Integer.parseInt(result[9]), Float.parseFloat(orderCompletePrice.getText()));
                    error.SQLError(res);
                    orderCompleteID.setText(null);
                    orderCompleteWeight.setText(null);
                    orderCompletePrice.setText(null);
                } else {
                    error.notAvailable();
                }
            }
        }else{
            error.SomethingMissing();
        }
    }//GEN-LAST:event_completeOrderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Order dialog = new Order(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeOrder;
    private javax.swing.JButton editOrder;
    private javax.swing.JFormattedTextField editOrderAdvance;
    private javax.swing.JTextField editOrderCaddress;
    private javax.swing.JTextField editOrderCname;
    private javax.swing.JFormattedTextField editOrderDate;
    private javax.swing.JTextField editOrderID;
    private javax.swing.JComboBox<String> editOrderItem;
    private javax.swing.JComboBox<String> editOrderMetal;
    private javax.swing.JTextArea editOrderNotes;
    private javax.swing.JFormattedTextField editOrderPh;
    private javax.swing.JFormattedTextField editOrderWeight_max;
    private javax.swing.JFormattedTextField editOrderWeight_min;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton newOrder;
    private javax.swing.JFormattedTextField newOrderAdvance;
    private javax.swing.JTextField newOrderCaddress;
    private javax.swing.JTextField newOrderCname;
    private javax.swing.JFormattedTextField newOrderDate;
    private javax.swing.JTextField newOrderID;
    private javax.swing.JComboBox<String> newOrderItem;
    private javax.swing.JComboBox<String> newOrderMetal;
    private javax.swing.JTextArea newOrderNotes;
    private javax.swing.JFormattedTextField newOrderPh;
    private javax.swing.JFormattedTextField newOrderWeight_max;
    private javax.swing.JFormattedTextField newOrderWeight_min;
    private javax.swing.JTextField orderCompleteID;
    private javax.swing.JFormattedTextField orderCompletePrice;
    private javax.swing.JFormattedTextField orderCompleteWeight;
    private javax.swing.JList<String> orderDetails;
    // End of variables declaration//GEN-END:variables
}
