/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelleryshop;

import java.awt.List;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jewelleryshop.object.ErrorHandler;
import jewelleryshop.object.Order_db;
import jewelleryshop.object.Work_db;

/**
 *
 * @author Admin
 */
public class Work extends javax.swing.JDialog {

    Work_db work = new Work_db();
    String date;
    ErrorHandler error = new ErrorHandler();
    Order_db order = new Order_db();

    /**
     * Creates new form Work
     */
    public Work(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());

        date = new SimpleDateFormat("dd-MM-yyyy").format(new Date(System.currentTimeMillis()));
        newDate.setText(date);
        workReturnDate.setText(date);
        gpDate.setText(date);
        String workID = work.getAutoIncriment();
        newWorkID.setText(workID);
        gpID.setText(workID);
        workReturnWorkerPaymentMetel.setEnabled(false);
        workReturnWorkerPaymentMoney.setEnabled(false);
        workReturnWorkerPaymentMetel.setText("0");
        workReturnWorkerPaymentMoney.setText("0");
        setWorkList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        newWorkID = new javax.swing.JTextField();
        newItemname = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jewelWork = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        newWorkType = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        newWorkTypeID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        newMetal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        newWorkWorkerID = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        newWorkMetalGiven = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        newDate = new javax.swing.JFormattedTextField();
        newWorkNotes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        workReturnID = new javax.swing.JTextField();
        workReturnWeight = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        workReturn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        workReturnWorkDetails = new javax.swing.JList<>();
        workReturnItemWeight = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        workReturnDate = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        workReturnPayYes = new javax.swing.JRadioButton();
        workReturnPayNo = new javax.swing.JRadioButton();
        workReturnWorkerPaymentMoney = new javax.swing.JFormattedTextField();
        workReturnWorkerPaymentMetel = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        gpItem = new javax.swing.JComboBox<>();
        gpDate = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        gpWeight = new javax.swing.JFormattedTextField();
        gpNote = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        gpSave = new javax.swing.JButton();
        gpMetal = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        gpRefurnish_id = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        gpID = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jewellery Work");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Work");

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 0));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Work ID");

        newWorkID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newWorkID.setForeground(new java.awt.Color(0, 102, 0));

        newItemname.setEditable(true);
        newItemname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newItemname.setForeground(new java.awt.Color(0, 102, 0));
        newItemname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ring", "Nackless", "Other" }));
        newItemname.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Item");

        jewelWork.setBackground(new java.awt.Color(0, 102, 0));
        jewelWork.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jewelWork.setForeground(new java.awt.Color(204, 255, 204));
        jewelWork.setText("Give to Worker");
        jewelWork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jewelWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jewelWorkMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        newWorkType.setEditable(true);
        newWorkType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newWorkType.setForeground(new java.awt.Color(0, 102, 0));
        newWorkType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order", "Refurnish", "New" }));
        newWorkType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                newWorkTypeItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 0));
        jLabel17.setText("Type");

        newWorkTypeID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newWorkTypeID.setForeground(new java.awt.Color(0, 102, 0));
        newWorkTypeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newWorkTypeIDKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 0));
        jLabel18.setText("Order ID");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(38, 38, 38)
                .addComponent(newWorkType, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(newWorkTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(newWorkType)
                    .addComponent(newWorkTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        newMetal.setEditable(true);
        newMetal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newMetal.setForeground(new java.awt.Color(0, 102, 0));
        newMetal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold", "Silver", "Bronze", "Copper" }));
        newMetal.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Metal");

        newWorkWorkerID.setForeground(new java.awt.Color(0, 102, 0));
        newWorkWorkerID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        newWorkWorkerID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setText("Worker ID");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(newMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(newWorkWorkerID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(newWorkWorkerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setText("Detais");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        newWorkMetalGiven.setForeground(new java.awt.Color(0, 102, 0));
        newWorkMetalGiven.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        newWorkMetalGiven.setText("0");
        newWorkMetalGiven.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newWorkMetalGiven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWorkMetalGivenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Date");

        newDate.setForeground(new java.awt.Color(0, 102, 0));
        newDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        newDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        newWorkNotes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newWorkNotes.setForeground(new java.awt.Color(0, 102, 0));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Notes");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 0));
        jLabel19.setText("Metal Given");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel20.setText("Worker Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jewelWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(newWorkID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(newDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(newItemname, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(newWorkMetalGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(newWorkNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newWorkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(newDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWorkMetalGiven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newItemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWorkNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jewelWork, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Jewellery Work", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Work ID");

        workReturnID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        workReturnID.setForeground(new java.awt.Color(0, 102, 0));
        workReturnID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                workReturnIDKeyReleased(evt);
            }
        });

        workReturnWeight.setForeground(new java.awt.Color(0, 102, 0));
        workReturnWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        workReturnWeight.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Return Weight");

        workReturn.setBackground(new java.awt.Color(0, 102, 0));
        workReturn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        workReturn.setForeground(new java.awt.Color(204, 255, 204));
        workReturn.setText("Return This Work");
        workReturn.setSelected(true);
        workReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workReturnMouseClicked(evt);
            }
        });

        jScrollPane4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        workReturnWorkDetails.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        workReturnWorkDetails.setForeground(new java.awt.Color(0, 102, 0));
        jScrollPane4.setViewportView(workReturnWorkDetails);

        workReturnItemWeight.setForeground(new java.awt.Color(0, 102, 0));
        workReturnItemWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        workReturnItemWeight.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 0));
        jLabel22.setText("Item Weight");

        workReturnDate.setForeground(new java.awt.Color(0, 102, 0));
        workReturnDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        workReturnDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        workReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workReturnDateActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 0));
        jLabel23.setText("Date");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 0));
        jLabel24.setText("Pay to Worker");

        workReturnPayYes.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(workReturnPayYes);
        workReturnPayYes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        workReturnPayYes.setForeground(new java.awt.Color(0, 102, 0));
        workReturnPayYes.setText("Yes");
        workReturnPayYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workReturnPayYesActionPerformed(evt);
            }
        });

        workReturnPayNo.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(workReturnPayNo);
        workReturnPayNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        workReturnPayNo.setForeground(new java.awt.Color(0, 102, 0));
        workReturnPayNo.setSelected(true);
        workReturnPayNo.setText("No");
        workReturnPayNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workReturnPayNoActionPerformed(evt);
            }
        });

        workReturnWorkerPaymentMoney.setForeground(new java.awt.Color(0, 102, 0));
        workReturnWorkerPaymentMoney.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        workReturnWorkerPaymentMoney.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        workReturnWorkerPaymentMetel.setForeground(new java.awt.Color(0, 102, 0));
        workReturnWorkerPaymentMetel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        workReturnWorkerPaymentMetel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 0));
        jLabel25.setText("Money");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 0));
        jLabel26.setText("Matel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workReturnDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(workReturnItemWeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(workReturnID)
                            .addComponent(workReturnWeight)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workReturnPayYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(workReturnPayNo)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(workReturnWorkerPaymentMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(workReturnWorkerPaymentMetel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workReturnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workReturnWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workReturnItemWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workReturnPayYes)
                            .addComponent(jLabel24)
                            .addComponent(workReturnPayNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workReturnWorkerPaymentMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(workReturnWorkerPaymentMetel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(workReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Jewellery Work Return", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        gpItem.setEditable(true);
        gpItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gpItem.setForeground(new java.awt.Color(0, 102, 0));
        gpItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ring", "Nackless", "Other" }));

        gpDate.setForeground(new java.awt.Color(0, 102, 0));
        gpDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        gpDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Item");

        gpWeight.setForeground(new java.awt.Color(0, 102, 0));
        gpWeight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0000"))));
        gpWeight.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        gpNote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gpNote.setForeground(new java.awt.Color(0, 102, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setText("Date");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 0));
        jLabel12.setText("Notes");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("Weight");

        gpSave.setBackground(new java.awt.Color(51, 102, 0));
        gpSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gpSave.setForeground(new java.awt.Color(204, 255, 204));
        gpSave.setText("Save");
        gpSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gpSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gpSaveMouseClicked(evt);
            }
        });

        gpMetal.setEditable(true);
        gpMetal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gpMetal.setForeground(new java.awt.Color(0, 102, 0));
        gpMetal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Bronz", "Copper" }));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setText("Metal");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 0));
        jLabel15.setText("Work ID");

        gpRefurnish_id.setForeground(new java.awt.Color(0, 102, 0));
        gpRefurnish_id.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        gpRefurnish_id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 0));
        jLabel16.setText("Reciving ID");

        jList1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 102, 0));
        jScrollPane3.setViewportView(jList1);

        gpID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        gpID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(gpNote)
                    .addComponent(gpRefurnish_id, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpItem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gpMetal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gpWeight, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gpID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(gpSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(gpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpRefurnish_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpSave)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gold Polishing", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jScrollPane2.setBackground(new java.awt.Color(204, 255, 204));

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Work #", "Worker #", "Item ID (#O32)", "Date", "Metal + Weight", "price+gold paid"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Active Work", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jewelWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jewelWorkMouseClicked
        if (!newWorkWorkerID.getText().isEmpty() && !newWorkID.getText().isEmpty() && !newDate.getText().isEmpty() && !newWorkMetalGiven.getText().isEmpty()) {
            int worker_id = Integer.parseInt(newWorkWorkerID.getText());
            int work_id = Integer.parseInt(newWorkID.getText());
            String date_start = newDate.getText();
            String work_type = newWorkType.getSelectedItem().toString();
            int type_id = newWorkTypeID.getText().isEmpty() ? 0 : Integer.parseInt(newWorkTypeID.getText());
            String item_name = newItemname.getSelectedItem().toString();
            String work_metal = newMetal.getSelectedItem().toString();
            float metal_given = Float.parseFloat(newWorkMetalGiven.getText());
            String notes = newWorkNotes.getText();
            if (work.isValidWorker(worker_id)) {
                int ret;
                switch (work_type) {
                    case "Order":
                        if (work.isValidOrder(type_id)) {
                            ret = work.insert(work_id, worker_id, item_name, work_type, type_id, date_start, work_metal, metal_given, notes);
                            error.SQLError(ret);
                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid Order ID#.", "Error...", JOptionPane.ERROR_MESSAGE);
                        }
                        break;
                    case "Refurnish":
                        if (work.isValidRefurnish(type_id)) {
                            ret = work.insert(work_id, worker_id, item_name, work_type, type_id, date_start, work_metal, metal_given, notes);
                            error.SQLError(ret);
                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid Refurnish ID#.", "Error...", JOptionPane.ERROR_MESSAGE);
                        }
                        break;
                    default:
                        ret = work.insert(work_id, worker_id, item_name, work_type, 0, date_start, work_metal, metal_given, notes);
                        error.SQLError(ret);
                        break;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Not a valid worker or worker dose nor exist.", "Error...", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            error.SomethingMissing();
        }
    }//GEN-LAST:event_jewelWorkMouseClicked

    private void newWorkTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_newWorkTypeItemStateChanged
        if (!newWorkType.getSelectedItem().equals("New")) {
            newWorkTypeID.setEnabled(true);
            newItemname.setEnabled(false);
            newMetal.setEnabled(false);
            jLabel18.setText(newWorkType.getSelectedItem() + " ID");
        } else {
            newWorkTypeID.setEnabled(false);
            newItemname.setEnabled(true);
            newMetal.setEnabled(true);
            newWorkTypeID.setText("0");
        }
    }//GEN-LAST:event_newWorkTypeItemStateChanged

    private void newWorkMetalGivenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWorkMetalGivenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newWorkMetalGivenActionPerformed

    private void newWorkTypeIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newWorkTypeIDKeyReleased
        if (newWorkType.getSelectedItem().toString().equals("Order")) {
            String details[] = order.getOrderDetails(newWorkTypeID.getText());
            newMetal.setSelectedItem(details[6]);
            newItemname.setSelectedItem(details[5]);
            jLabel4.setText(details[2] + ", " + details[6] + ", " + details[7] + "gm - " + details[8] + "gm, " + details[13]);
        }
    }//GEN-LAST:event_newWorkTypeIDKeyReleased

    private void workReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workReturnDateActionPerformed

    private void workReturnIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workReturnIDKeyReleased
        if (!workReturnID.getText().isEmpty()) {
            String details[] = work.getDetails(workReturnID.getText());

            DefaultListModel<String> lm = new DefaultListModel<>();
            lm.addElement("Work ID            : " + details[0]);
            lm.addElement("Worker ID        : " + details[1]);
            lm.addElement(details[2] + " ID           : " + details[3]);
            lm.addElement("Item Name      : " + details[4]);
            lm.addElement("Date of Start    : " + details[5]);
            lm.addElement("Date of Return: " + details[6]);
            lm.addElement(details[7] + " Given     : " + details[8]);
            lm.addElement(details[7] + " Return   : " + details[9]);
            lm.addElement("Item Weight     : " + details[10]);
            lm.addElement("Paid(Money)    : " + details[11]);
            lm.addElement("Paid(" + details[7] + ")     : " + details[12]);
            lm.addElement("Notes : ");
            lm.addElement(details[13]);
            workReturnWorkDetails.setModel(lm);
            jLabel26.setText(details[7]);
        }
    }//GEN-LAST:event_workReturnIDKeyReleased

    private void workReturnPayNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workReturnPayNoActionPerformed
        workReturnWorkerPaymentMetel.setEnabled(false);
        workReturnWorkerPaymentMoney.setEnabled(false);
        workReturnWorkerPaymentMetel.setText("0");
        workReturnWorkerPaymentMoney.setText("0");
    }//GEN-LAST:event_workReturnPayNoActionPerformed

    private void workReturnPayYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workReturnPayYesActionPerformed
        workReturnWorkerPaymentMetel.setEnabled(true);
        workReturnWorkerPaymentMoney.setEnabled(true);
    }//GEN-LAST:event_workReturnPayYesActionPerformed

    private void workReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workReturnMouseClicked
        if (!workReturnID.getText().isEmpty() && !workReturnDate.getText().isEmpty() && !workReturnWeight.getText().isEmpty() && !workReturnItemWeight.getText().isEmpty()) {
            try {
                int work_id = Integer.parseInt(workReturnID.getText());
                String work_complete_date = workReturnDate.getText();
                float return_wt = Float.parseFloat(workReturnWeight.getText());
                float return_item_wt = Float.parseFloat(workReturnItemWeight.getText());
                boolean pay_to_worker = workReturnPayYes.isSelected();
                int payment_money = Integer.parseInt(workReturnWorkerPaymentMoney.getText());
                float payment_metal = Float.parseFloat(workReturnWorkerPaymentMetel.getText());
                String details[] = work.getDetails(workReturnID.getText());
                if (details[6].equals("0")) {
                    int res = work.complete(work_id, work_complete_date, return_wt, return_item_wt, pay_to_worker, payment_money, payment_metal);
                    error.SQLError(res);
                } else {
                    error.alreadyCompleted();
                }
            } catch (NullPointerException ex) {
                System.out.println("jewelleryshop.Work.workReturnMouseClicked(): " + ex.getMessage());
            }
        } else {
            error.SomethingMissing();
        }
    }//GEN-LAST:event_workReturnMouseClicked

    private void gpSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gpSaveMouseClicked
        if (!gpID.getText().isEmpty() && !gpDate.getText().isEmpty() && !gpWeight.getText().isEmpty() && !gpRefurnish_id.getText().isEmpty()) {
            int id = Integer.parseInt(gpID.getText());
            String Date = gpDate.getText();
            float Weight = Float.parseFloat(gpWeight.getText());
            String metal = gpMetal.getSelectedItem().toString();
            String item = gpItem.getSelectedItem().toString();
            int refurnish_id = Integer.parseInt(gpRefurnish_id.getText());
            String notes = gpNote.getText();

            if (work.isValidRefurnish(refurnish_id)) {
                int ret = work.insert(id, 0, item, "Refurnish", refurnish_id, Date, metal, Weight, notes);
                error.SQLError(ret);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Refurnish ID#.", "Error...", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            error.SomethingMissing();
        }
    }//GEN-LAST:event_gpSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Work.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Work dialog = new Work(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField gpDate;
    private javax.swing.JFormattedTextField gpID;
    private javax.swing.JComboBox<String> gpItem;
    private javax.swing.JComboBox<String> gpMetal;
    private javax.swing.JTextField gpNote;
    private javax.swing.JFormattedTextField gpRefurnish_id;
    private javax.swing.JButton gpSave;
    private javax.swing.JFormattedTextField gpWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jewelWork;
    private javax.swing.JFormattedTextField newDate;
    private javax.swing.JComboBox<String> newItemname;
    private javax.swing.JComboBox<String> newMetal;
    private javax.swing.JTextField newWorkID;
    private javax.swing.JFormattedTextField newWorkMetalGiven;
    private javax.swing.JTextField newWorkNotes;
    private javax.swing.JComboBox<String> newWorkType;
    private javax.swing.JTextField newWorkTypeID;
    private javax.swing.JFormattedTextField newWorkWorkerID;
    private javax.swing.JButton workReturn;
    private javax.swing.JFormattedTextField workReturnDate;
    private javax.swing.JTextField workReturnID;
    private javax.swing.JFormattedTextField workReturnItemWeight;
    private javax.swing.JRadioButton workReturnPayNo;
    private javax.swing.JRadioButton workReturnPayYes;
    private javax.swing.JFormattedTextField workReturnWeight;
    private javax.swing.JList<String> workReturnWorkDetails;
    private javax.swing.JFormattedTextField workReturnWorkerPaymentMetel;
    private javax.swing.JFormattedTextField workReturnWorkerPaymentMoney;
    // End of variables declaration//GEN-END:variables

    private void setWorkList() {
        List[] listString = work.getAllWork();
    }

}
