/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jewelleryshop.database;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import jewelleryshop.Login;

/**
 *
 * @author Admin
 */
public class BackupDatabase extends javax.swing.JDialog {

    /**
     * Creates new form SavePrompt
     */
    public BackupDatabase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        System.out.println(getSQLpath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databaseBackup = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        databaseBackup.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        databaseBackup.setApproveButtonText("Backup");
        databaseBackup.setDialogTitle("Database Backup");
        databaseBackup.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        databaseBackup.setName(""); // NOI18N
        databaseBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(databaseBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(databaseBackup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void databaseBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseBackupActionPerformed

        if (evt.getActionCommand().equals("CancelSelection")) {
            this.dispose();
        } else {
            if (evt.getActionCommand().equals("ApproveSelection")) {
                String file = databaseBackup.getSelectedFile().toString();
                String cmd = getSQLpath() + "mysqldump.exe -u " + Login.user;
                if (!Login.pass.isEmpty()) {
                    cmd = cmd + " -p " + Login.pass;
                }
                cmd = cmd + " --database shop_database -r " + file + ".sql";
                try {
                    Process cmdProcess = Runtime.getRuntime().exec(cmd);
                    int processState = cmdProcess.waitFor();
                    if (processState == 0) {
                        System.out.println("Sucess");
                    } else {
                        System.out.println("Error");
                    }
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(BackupDatabase.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(BackupDatabase.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_databaseBackupActionPerformed
    public String getSQLpath() {

        String server = Login.server;
        String port = Login.port;
        String user = Login.user;
        String pass = Login.pass;
        String conn_str = "jdbc:mysql://" + server + ":" + port + "/shop_database";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(conn_str, user, pass);
            Statement statment = con.createStatement();
            String sql = "select @@basedir";
            ResultSet res = statment.executeQuery(sql);
            String ret = null;
            while (res.next()) {
                ret = res.getString(1);
            }
            return ret + "/bin/";
        } catch (SQLException ex) {
            System.err.println("Order.getAutoIncriment(), SQLException (" + ex.getErrorCode() + ") : " + ex.getMessage());
            return null;
        } catch (ClassNotFoundException ex) {
            System.err.println("Order.getAutoIncriment(), ClassNotFoundException : " + ex.getMessage());
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackupDatabase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackupDatabase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackupDatabase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackupDatabase.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BackupDatabase dialog = new BackupDatabase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser databaseBackup;
    // End of variables declaration//GEN-END:variables
}
